"""baseline schema for CAR reporting platform

Creates the full governance schema from the SQLAlchemy metadata. Single-pack
MVP baseline; subsequent changes should use autogenerated migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-09
"""
from alembic import op

import app.models  # noqa: F401  register models on Base
from app.core.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
